backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Store"
    name: "store"
    editor:
      preview: false
    files:
      - label: "Products List"
        name: "products-list"
        file: "content/serve/products.json"
        fields:
          - label: Product
            name: product
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: 'Description', name: 'description', widget: 'string'}
              - {label: 'Price', name: 'price', widget: 'number'}
              - {label: 'Featured Image', name: 'image', widget: 'image'}

      - label: "Announcements"
        name: "announcements"
        file: "content/serve/announcements.json"
        fields:
          - label: Post
            name: post
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: 'Description', name: 'description', widget: 'string'}
              - {label: 'Date', name: 'date', widget: 'date'}
              
